"""Supervised training entrypoint for STB on MITFLD."""

from __future__ import annotations

import copy
import json
import logging
from datetime import datetime
from pathlib import Path

import torch
from torch import nn
from torch.utils.data import DataLoader
import click

from kpi.datasets.mitfld import MITFLD

from kpi.utils import TextLabelSequenceDataset, set_seed, text_label_collate_fn
from kpi.utils.stb_supervised import (
    ProcessedTextLabelDataset,
    compute_pos_weight,
    evaluate_boundary_metrics,
    evaluate_boundary_metrics_processed,
    load_processed_samples,
    parse_json_kwargs,
    processed_text_label_collate_fn,
    resolve_device,
    run_epoch,
    select_best_boundary_threshold,
    select_best_boundary_threshold_processed,
    split_processed_dataset,
    validate_split_ratios,
)
from kpi.utils.logconfig import setup_logging

from kpi.models.STB import LectureSegmentationModel

SEED = 2024
logger = logging.getLogger(__name__)


def _build_threshold_grid(min_value: float, max_value: float, step: float) -> list[float]:
    thresholds: list[float] = []
    current = min_value
    while current <= max_value + 1e-12:
        thresholds.append(float(round(current, 10)))
        current += step
    if not thresholds:
        thresholds = [float(min_value)]
    return thresholds

@click.command()
@click.option(
    "--dataset_path",
    required=False,
    type=str,
    help="Path to the dataset root directory.",
)
@click.option(
    "--processed_dataset_path",
    type=str,
    default=None,
    help="Path to processed text-label dataset generated by export_text_label_dataset.py.",
)
@click.option(
    "--encoder_weights_path",
    type=str,
)
@click.option(
    "--transformer_weights_path",
    type=str,
)
@click.option(
    "--detector_weights_path",
    type=str,
)
@click.option(
    "--encoder_kwargs",
    type=str,
    default="{}",
    help="JSON string of keyword arguments for the SentenceEncoder.",
)
@click.option(
    "--transformer_kwargs",
    type=str,
    default="{}",
    help="JSON string of keyword arguments for the GlobalTransformer.",
)
@click.option(
    "--detector_kwargs",
    type=str,
    default="{}",
    help="JSON string of keyword arguments for the BoundaryDetector.",
)
@click.option(
    "--log_level",
    type=str,
    default="DID",
    help="Logging level (e.g., INFO, DEBUG, WARNING, ERROR, CRITICAL).",
)
@click.option("--seed", type=int, default=SEED, show_default=True)
@click.option("--split_seed", type=int, default=SEED, show_default=True)
@click.option("--train_ratio", type=float, default=0.7, show_default=True)
@click.option("--val_ratio", type=float, default=0.15, show_default=True)
@click.option("--test_ratio", type=float, default=0.15, show_default=True)
@click.option("--epochs", type=int, default=20, show_default=True)
@click.option("--batch_size", type=int, default=4, show_default=True)
@click.option("--lr", type=float, default=1e-4, show_default=True)
@click.option("--weight_decay", type=float, default=1e-2, show_default=True)
@click.option("--grad_clip_norm", type=float, default=1.0, show_default=True)
@click.option("--boundary_threshold", type=float, default=0.5, show_default=True)
@click.option("--local_max_k", type=int, default=2, show_default=True)
@click.option("--threshold_min", type=float, default=0.0, show_default=True)
@click.option("--threshold_max", type=float, default=1.0, show_default=True)
@click.option("--threshold_step", type=float, default=0.05, show_default=True)
@click.option("--f1_threshold", type=float, default=10, show_default=True)
@click.option("--iou_fps", type=int, default=10, show_default=True)
@click.option("--mof_fps", type=int, default=10, show_default=True)
@click.option("--device", type=str, default="auto", show_default=True)
@click.option("--num_workers", type=int, default=0, show_default=True)
@click.option("--output_dir", type=str, default="artifacts/stb_supervised", show_default=True)
@click.option("--run_name", type=str, default=None)
@click.option("--save_best/--no-save_best", default=True, show_default=True)
@click.option("--save_last/--no-save_last", default=True, show_default=True)
@click.option("--pos_weight_normalizer", type=float, default=1.0, show_default=True)
@click.option("--freeze_encoder_epochs", type=int, default=None)
@click.option("--freeze_transformer_epochs", type=int, default=None)
@click.option("--freeze_detector_epochs", type=int, default=None)
def run_supervised_training(
    dataset_path: str | None = None,
    processed_dataset_path: str | None = None,
    encoder_weights_path: str = None,
    transformer_weights_path: str = None,
    detector_weights_path: str = None,
    encoder_kwargs: str = "{}",
    transformer_kwargs: str = "{}",
    detector_kwargs: str = "{}",
    log_level: str = "DID",
    seed: int = SEED,
    split_seed: int = SEED,
    train_ratio: float = 0.7,
    val_ratio: float = 0.15,
    test_ratio: float = 0.15,
    epochs: int = 20,
    batch_size: int = 4,
    lr: float = 1e-4,
    pos_weight_normalizer: float = 1.0,
    weight_decay: float = 1e-2,
    grad_clip_norm: float = 1.0,
    boundary_threshold: float = 0.5,
    local_max_k: int = 3,
    threshold_min: float = 0.0,
    threshold_max: float = 1.0,
    threshold_step: float = 0.05,
    f1_threshold: float = 10,
    iou_fps: int = 10,
    mof_fps: int = 10,
    device: str = "auto",
    num_workers: int = 0,
    output_dir: str = "artifacts/stb_supervised",
    run_name: str | None = None,
    save_best: bool = True,
    save_last: bool = True,
    freeze_encoder_epochs: int | None = None,
    freeze_transformer_epochs: int | None = None,
    freeze_detector_epochs: int | None = None,
) -> None:
    # create the dir if not exist
    output_root = Path(output_dir)
    output_root.mkdir(parents=True, exist_ok=True)

    setup_logging(log_level, output_dir)
    validate_split_ratios(train_ratio, val_ratio, test_ratio)

    if bool(dataset_path) == bool(processed_dataset_path):
        raise click.BadParameter("Provide exactly one of --dataset_path or --processed_dataset_path")

    if epochs <= 0:
        raise click.BadParameter("epochs must be > 0")
    if batch_size <= 0:
        raise click.BadParameter("batch_size must be > 0")
    if local_max_k < 0:
        raise click.BadParameter("local_max_k must be >= 0")
    if not (0.0 <= threshold_min <= threshold_max <= 1.0):
        raise click.BadParameter("Require 0 <= threshold_min <= threshold_max <= 1")
    if threshold_step <= 0:
        raise click.BadParameter("threshold_step must be > 0")

    freeze_plan = {
        "encoder": freeze_encoder_epochs,
        "transformer": freeze_transformer_epochs,
        "detector": freeze_detector_epochs,
    }
    for module_name, freeze_epochs in freeze_plan.items():
        if freeze_epochs is not None and freeze_epochs < 0:
            raise click.BadParameter(f"freeze_{module_name}_epochs must be >= 0")

    set_seed(seed)
    model_device = resolve_device(device)
    logger.info("Using device: %s", model_device)

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    run_stem = run_name or f"stb_mitfld_{timestamp}"

    encoder_kwargs_dict = parse_json_kwargs("encoder_kwargs", encoder_kwargs)
    transformer_kwargs_dict = parse_json_kwargs("transformer_kwargs", transformer_kwargs)
    detector_kwargs_dict = parse_json_kwargs("detector_kwargs", detector_kwargs)


    using_processed_dataset = processed_dataset_path is not None
    test_data = None

    if using_processed_dataset:
        logger.info("Loading processed dataset from %s", processed_dataset_path)
        samples = load_processed_samples(processed_dataset_path)
        processed_dataset = ProcessedTextLabelDataset(samples)
        train_ds, val_ds, test_ds = split_processed_dataset(
            dataset=processed_dataset,
            ratios=[train_ratio, val_ratio, test_ratio],
            seed=split_seed,
        )
        collate_fn = processed_text_label_collate_fn
    else:
        logger.info("Loading MITFLD dataset from %s", dataset_path)
        dataset = MITFLD(dataset_path)
        train_data, val_data, test_data = dataset.random_split(
            [train_ratio, val_ratio, test_ratio],
            seed=split_seed,
        )

        train_ds = TextLabelSequenceDataset(train_data)
        val_ds = TextLabelSequenceDataset(val_data)
        test_ds = TextLabelSequenceDataset(test_data)
        collate_fn = text_label_collate_fn

    train_loader = DataLoader(
        train_ds,
        batch_size=batch_size,
        shuffle=True,
        collate_fn=collate_fn,
        num_workers=num_workers,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=batch_size,
        shuffle=False,
        collate_fn=collate_fn,
        num_workers=num_workers,
    )
    test_loader = DataLoader(
        test_ds,
        batch_size=batch_size,
        shuffle=False,
        collate_fn=collate_fn,
        num_workers=num_workers,
    )

    # model setup
    model = LectureSegmentationModel(
        encoder_checkpoint=encoder_weights_path,
        transformer_checkpoint=transformer_weights_path,
        detector_checkpoint=detector_weights_path,
        encoder_kwargs=encoder_kwargs_dict,
        transformer_kwargs=transformer_kwargs_dict,
        detector_kwargs=detector_kwargs_dict,
    ).to(model_device)
    logger.info("Model config: %s", model.get_config())

    freeze_log_entries: list[str] = []
    for module_name, freeze_epochs in freeze_plan.items():
        if freeze_epochs is not None and freeze_epochs > 0:
            getattr(model, module_name).requires_grad_(False)
            if freeze_epochs >= epochs:
                freeze_log_entries.append(f"{module_name}:all {epochs} epochs")
            else:
                freeze_log_entries.append(f"{module_name}:first {freeze_epochs} epochs")
    if freeze_log_entries:
        logger.info("Freeze schedule -> %s", ", ".join(freeze_log_entries))


    # training setup
    pos_weight_value = compute_pos_weight(train_ds)
    pos_weight_value = pos_weight_value/pos_weight_normalizer
    pos_weight = torch.tensor(pos_weight_value, dtype=torch.float32, device=model_device)
    logger.info("Using BCE pos_weight=%.4f", pos_weight_value)

    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight, reduction="none")
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

    best_state = None
    best_val_loss = float("inf")
    best_val_f1 = float("-inf")
    best_epoch = 0
    history: list[dict[str, float | int]] = []

    # training loop
    for epoch_idx in range(1, epochs + 1):
        for module_name, freeze_epochs in freeze_plan.items():
            if (
                freeze_epochs is not None
                and freeze_epochs > 0
                and freeze_epochs < epochs
                and epoch_idx == freeze_epochs + 1
            ):
                getattr(model, module_name).requires_grad_(True)
                logger.info("Unfroze %s at epoch %d", module_name, epoch_idx)

        train_stats = run_epoch(
            model=model,
            loader=train_loader,
            criterion=criterion,
            device=model_device,
            optimizer=optimizer,
            grad_clip_norm=grad_clip_norm,
        )
        with torch.no_grad():
            val_stats = run_epoch(
                model=model,
                loader=val_loader,
                criterion=criterion,
                device=model_device,
                optimizer=None,
            )

        history.append(
            {
                "epoch": epoch_idx,
                "train_loss": train_stats["loss"],
                "val_loss": val_stats["loss"],
            }
        )

        logger.info(
            "epoch=%d train_loss=%.6f val_loss=%.6f",
            epoch_idx,
            train_stats["loss"],
            val_stats["loss"],
        )

        if val_stats["loss"] < best_val_loss:
            best_val_loss = val_stats["loss"]
            best_val_f1 = float("nan")
            best_epoch = epoch_idx
            best_state = copy.deepcopy(model.state_dict())
            if save_best:
                best_path = output_root / f"{run_stem}_best.pt"
                model.save_checkpoint(best_path)
                logger.info("Saved best checkpoint to %s", best_path)

    if best_state is not None:
        model.load_state_dict(best_state)

    if save_last:
        last_path = output_root / f"{run_stem}_last.pt"
        model.save_checkpoint(last_path)
        logger.info("Saved last checkpoint to %s", last_path)

    threshold_candidates = _build_threshold_grid(
        min_value=threshold_min,
        max_value=threshold_max,
        step=threshold_step,
    )
    logger.info(
        "Selecting boundary threshold on val split: min=%.3f max=%.3f step=%.3f (%d candidates)",
        threshold_min,
        threshold_max,
        threshold_step,
        len(threshold_candidates),
    )

    selected_boundary_threshold = boundary_threshold
    selected_val_f1 = float("-inf")
    threshold_sweep: list[dict[str, float]] = []
    if using_processed_dataset:
        (
            selected_boundary_threshold,
            selected_val_f1,
            threshold_sweep,
        ) = select_best_boundary_threshold_processed(
            model=model,
            loader=val_loader,
            device=model_device,
            threshold_candidates=threshold_candidates,
            local_max_k=local_max_k,
            f1_threshold=f1_threshold,
        )
    else:
        (
            selected_boundary_threshold,
            selected_val_f1,
            threshold_sweep,
        ) = select_best_boundary_threshold(
            model=model,
            dataset_split=val_data,
            loader=val_loader,
            device=model_device,
            threshold_candidates=threshold_candidates,
            local_max_k=local_max_k,
            f1_threshold=f1_threshold,
        )

    best_val_f1 = selected_val_f1
    logger.info(
        "Selected boundary threshold=%.4f from val (best F1=%.6f)",
        selected_boundary_threshold,
        selected_val_f1,
    )

    if using_processed_dataset:
        test_boundary_scores = evaluate_boundary_metrics_processed(
            model=model,
            loader=test_loader,
            device=model_device,
            boundary_threshold=selected_boundary_threshold,
            local_max_k=local_max_k,
            f1_threshold=f1_threshold,
            iou_fps=iou_fps,
            mof_fps=mof_fps,
        )
    else:
        test_boundary_scores = evaluate_boundary_metrics(
            model=model,
            dataset_split=test_data,
            loader=test_loader,
            device=model_device,
            boundary_threshold=selected_boundary_threshold,
            local_max_k=local_max_k,
            f1_threshold=f1_threshold,
            iou_fps=iou_fps,
            mof_fps=mof_fps,
        )

    logger.info("Test boundary metrics (F1 as main):")
    for metric_name, value in test_boundary_scores.items():
        logger.info("%s = %.6f", metric_name, value)

    summary = {
        "run_name": run_stem,
        "seed": seed,
        "split_seed": split_seed,
        "device": str(model_device),
        "best_epoch": best_epoch,
        "best_val_loss": best_val_loss,
        "best_val_f1": best_val_f1,
        "selected_boundary_threshold": selected_boundary_threshold,
        "threshold_sweep": threshold_sweep,
        "test_metrics": test_boundary_scores,
        "history": history,
        "options": {
            "dataset_path": dataset_path,
            "processed_dataset_path": processed_dataset_path,
            "epochs": epochs,
            "batch_size": batch_size,
            "lr": lr,
            "weight_decay": weight_decay,
            "boundary_threshold_init": boundary_threshold,
            "threshold_min": threshold_min,
            "threshold_max": threshold_max,
            "threshold_step": threshold_step,
            "boundary_threshold": selected_boundary_threshold,
            "local_max_k": local_max_k,
            "f1_threshold": f1_threshold,
            "iou_fps": iou_fps,
            "mof_fps": mof_fps,
            "train_ratio": train_ratio,
            "val_ratio": val_ratio,
            "test_ratio": test_ratio,
            "encoder_weights_path": encoder_weights_path,
            "transformer_weights_path": transformer_weights_path,
            "detector_weights_path": detector_weights_path,
            "freeze_encoder_epochs": freeze_encoder_epochs,
            "freeze_transformer_epochs": freeze_transformer_epochs,
            "freeze_detector_epochs": freeze_detector_epochs,
        },
    }
    summary_path = output_root / f"{run_stem}_summary.json"
    with summary_path.open("w", encoding="utf-8") as fp:
        json.dump(summary, fp, indent=2, ensure_ascii=True)
    logger.info("Saved training summary to %s", summary_path)


if __name__ == "__main__":
    run_supervised_training()