"""Data-loading helpers for STB pre-training (no segment labels required)."""

from __future__ import annotations

import logging
from typing import Any

import torch
from torch.utils.data import Dataset

logger = logging.getLogger(__name__)


class LecturePretrainDataset(Dataset):
    """Dataset of sentence lists for STB pre-training.

    No segment boundary labels are needed — only raw sentence texts.

    Args:
        lectures: List of documents, each a non-empty list of sentence strings.
            Documents with fewer than 2 sentences are silently discarded.
    """

    def __init__(self, lectures: list[list[str]]) -> None:
        self.lectures: list[list[str]] = [s for s in lectures if len(s) >= 2]
        logger.info(
            "LecturePretrainDataset: retained %d / %d lectures (min 2 sentences)",
            len(self.lectures),
            len(lectures),
        )

    def __len__(self) -> int:
        return len(self.lectures)

    def __getitem__(self, idx: int) -> dict[str, Any]:
        return {"text": self.lectures[idx]}

    # ------------------------------------------------------------------
    # Factory helpers for easy construction from existing dataset objects
    # ------------------------------------------------------------------

    @classmethod
    def from_base_dataset(cls, dataset: Any) -> "LecturePretrainDataset":
        """Build from a single :class:`~kpi.datasets.base_dataset.Dataset`.

        Iterates over ``(video, frags)`` pairs and extracts sentence texts
        from ``video.srt``.

        Args:
            dataset: Any object iterable as ``(Video, frags)`` pairs where
                ``Video.srt`` returns a sequence of objects with a ``.text``
                attribute.
        """
        lectures: list[list[str]] = []
        for video, _frags in dataset:
            sentences = [srt.text for srt in video.srt]
            if len(sentences) >= 2:
                lectures.append(sentences)
        logger.info(
            "LecturePretrainDataset.from_base_dataset: extracted %d lectures", len(lectures)
        )
        return cls(lectures)

    @classmethod
    def from_datasets(cls, datasets: list[Any]) -> "LecturePretrainDataset":
        """Merge multiple dataset objects into a single pre-training dataset.

        Useful for adding new data sources later (e.g. AVLecture, custom
        recordings) without changing any other code — just append to the list.

        Args:
            datasets: List of objects iterable as ``(Video, frags)`` pairs.
        """
        all_lectures: list[list[str]] = []
        for ds in datasets:
            for video, _frags in ds:
                sentences = [srt.text for srt in video.srt]
                if len(sentences) >= 2:
                    all_lectures.append(sentences)
        logger.info(
            "LecturePretrainDataset.from_datasets: extracted %d lectures from %d sources",
            len(all_lectures),
            len(datasets),
        )
        return cls(all_lectures)

    @classmethod
    def from_processed_files(cls, file_paths: list[str]) -> "LecturePretrainDataset":
        """Build from one or multiple processed `.pt` dataset files.

        Reads samples generated by `export_text_label_dataset.py` directly,
        avoiding raw video/srt directory scans.

        Args:
            file_paths: List of file paths to `.pt` dataset files.
        """
        all_lectures: list[list[str]] = []
        for path in file_paths:
            payload = torch.load(path, map_location="cpu")
            if isinstance(payload, dict) and "samples" in payload:
                samples = payload["samples"]
            elif isinstance(payload, list):
                samples = payload
            else:
                raise ValueError(f"Unsupported processed dataset payload in {path}")

            for sample in samples:
                sentences = list(sample.get("text", []))
                if len(sentences) >= 2:
                    all_lectures.append(sentences)
        logger.info(
            "LecturePretrainDataset.from_processed_files: loaded %d lectures from %d file(s)",
            len(all_lectures),
            len(file_paths),
        )
        return cls(all_lectures)


def pretrain_collate_fn(batch: list[dict[str, Any]]) -> dict[str, Any]:
    """Collate a list of :class:`LecturePretrainDataset` items into a batch.

    The collated batch contains the raw text lists (no padding at the text
    level — padding is handled by the model's sentence encoder) and an integer
    ``lengths`` tensor used by the transformer and perturbation helpers.

    Returns:
        dict with keys:
            ``text``     ``list[list[str]]`` — one list of sentences per document.
            ``lengths``  ``Tensor[B]`` — number of sentences in each document.
    """
    texts = [item["text"] for item in batch]
    lengths = torch.tensor([len(t) for t in texts], dtype=torch.long)
    return {"text": texts, "lengths": lengths}
